name: Backend Production Deploy (CD)

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Backend Deploy
    runs-on: shook-runner
    
    steps:
    - name: Show current user name
      shell: bash
      run: whoami
    - name: Checkout Source Code
      uses: actions/checkout@v2
    - name: Grant execute permission to gradlew
      shell: bash
      run: chmod +x backend/gradlew
    - name: Check Java Version
      shell: bash
      run: java --version
    - name: Gradlew bootJar
      shell: bash
      run: |
        cd backend
        ./gradlew bootJar
        cd ..
    - name: Copy Jar
      shell: bash
      run: cp backend/build/libs/shook-0.0.1-SNAPSHOT.jar ~/application-jar
    - name: Remove Repository 
      shell: bash
      run: |
        cd ../..
        rm -rf test-2023-shook
    - name: Move to home
      shell: bash
      run: |
        cd /Users/split
        pwd
    - name: Backend Deploy
      shell: bash
      run: bash backend-deploy.sh
