name: Backend Production Deploy (CD)

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Backend Deploy
    runs-on: shook-runner
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SUBMODULE_PAT }}
        submodules: recursive
    - name: Grant execute permission to gradlew
      shell: bash
      run: chmod +x 2023-shook/backend/gradlew
    - name: Gradlew bootJar
      shell: bash
      run: 2023-shook/backend/gradlew bootJar
    - name: Copy Jar
      shell: bash
      run: cp 2023-shook/backend/build/libs/shook-0.0.1-SNAPSHOT.jar ~/application-jar
    - name: Remove Repository 
      shell: bash
      run: rm -rf 2023-shook
    - name: Backend Deploy
      shell: bash
      run: bash ~/backend-deploy.sh
